### ISSUE TITLE
duplicate files - investigate

### ISSUE THREAD

**Issue by klinga** [IJPNY/metadata_quality_collection_151#1]
files and identifiers appearing more than once in data set for collection 151

	Identifier	File_Name
20	701-151-005-2534-001	701-151-005-2534-001.tif
406	701-151-005-2534-001	701-151-005-2534-001.tif

14	701-151-005-2573-001	701-151-005-2573-001.tif
33	701-151-005-2573-001	701-151-005-2573-001.tif

174	701-151-005-2673-001	701-151-005-2673-001.tif
259	701-151-005-2673-001	701-151-005-2673-001.tif
174	701-151-005-2673-001	701-151-005-2673-002.tif
259	701-151-005-2673-001	701-151-005-2673-002.tif

0	701-151-005-3057-005	701-151-005-3057-005.tif
501	701-151-005-3057-005	701-151-005-3057-005.tif

3	701-151-005-3061-001	701-151-005-3061-001.tif
264	701-151-005-3061-001	701-151-005-3061-001.tif

4	701-151-005-4949-001	701-151-005-4949-001.tif
107	701-151-005-4949-001	701-151-005-4949-001.tif

**Comment by Marek-K-Zielinski** [comment]
Those are duplicates of items. Extract the field dc.identifier.uri and use it to access the records.

**Comment by Marek-K-Zielinski** [comment]
11/21/17 - duplicate documents withdrawn in DSpace

**Comment by klinga** [comment]
fixed
