### ISSUE TITLE
duplicate identifiers

### ISSUE THREAD

**Issue by klinga** [IJPNY/metadata_quality_collection_151#3]
This is probably related to #1 issue
duplicate identifiers found in the csv file

'701-151-005-2534-001', '701-151-005-2573-001', '701-151-005-2673-001', '701-151-005-3057-005', '701-151-005-3061-001', '701-151-005-4949-001'

**Comment by Marek-K-Zielinski** [comment]
Same as Issue 4, duplicate documents in DSpace
