### ISSUE TITLE
Suspicious identifiers

### ISSUE THREAD

**Issue by klinga** [IJPNY/metadata_quality_collection_151#4]
Longer than usual identifiers:
701-151-005-2696-001-001
701-151-005-2830-001-001

**Comment by Marek-K-Zielinski** [comment]
Those are OK. Page 001 subpage 001. 
Images have the "folder" or item identifier e.g. -2696
Sometimes folder has several images -2696-001, 2696-002 etc. Those are "pages"
Sometimes a group of image gets a single page ID. In this case we create "subpages"

**Comment by klinga** [comment]
got it
